---
title: "Análisis inicial de bases"
output: html_document
date: "2025-10-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(janitor)
library(tidyverse)
library(skimr)
library (readxl)
```

```{r Convencionales 2021}
colnames(Gasto_Candidatos_Constitucionales_2021)

gasto_constituyente_1 <- Gasto_Candidatos_Constitucionales_2021 %>% select(...2, ...3, ...9, ...19, ...20)

gasto_constituyentes_2 <- gasto_constituyente_1 %>% rename(autoridad_electa = ...2,
                      region = ...3,
                      partido_politico = ...9,
                      glosa_del_gasto = ...19,
                      monto_en_pesos = ...20)

gasto_constituyentes_2 <- gasto_constituyentes_2 %>% filter(autoridad_electa == "CONVENCIONAL CONSTITUYENTE")

gasto_digital_constituyentes_2021 <- gasto_constituyentes_2 %>% filter(str_detect(glosa_del_gasto, regex("digital", ignore_case = T)))

rm(gasto_constituyente_1, gasto_constituyentes_2)
```

```{r Parlamentarias 2021}
colnames(Gasto_Campañas_Parlamentarias_2021)

gasto_parlamentarias_1 <- Gasto_Campañas_Parlamentarias_2021 %>% select(...2,...3,...9,...19,...21)

gasto_parlamentarias_2 <- gasto_parlamentarias_1 %>% rename(autoridad_electa = ...2,
                      region = ...3,
                      partido_politico = ...9,
                      glosa_del_gasto = ...19,
                      monto = ...21)

gasto_digital_parlamentarias_2021 <- gasto_parlamentarias_2 %>% filter(str_detect(glosa_del_gasto, regex("digital", ignore_case = T)),
                               autoridad_electa %in% c("SENADOR", "DIPUTADO"))

rm(gasto_parlamentarias_1, gasto_parlamentarias_2)
```

```{r Parlamentarias 2017}
colnames(Gasto_Campaña_Parlamentarias_2017)

gasto_parlamentarias_1 <- Gasto_Campaña_Parlamentarias_2017 %>% select("PLANILLA DE GASTOS ELECCIONES PRESIDENCIAL Y PARLAMENTARIAS", ...2, ...8,...18, ...19)

gasto_parlamentarias_2 <- gasto_parlamentarias_1 %>% rename(autoridad_electa = "PLANILLA DE GASTOS ELECCIONES PRESIDENCIAL Y PARLAMENTARIAS",
                          region = ...2,
                          partido_politico = ...8,
                          glosa_del_gasto = ...18,
                          monto = ...19)

gasto_digital_parlamentarias_2017 <- gasto_parlamentarias_2 %>% filter(str_detect(glosa_del_gasto, regex("digital",ignore_case=T)),
                                   autoridad_electa %in% c("SENADOR", "DIPUTADO"))
rm(gasto_parlamentarias_1, gasto_parlamentarias_2)
```

```{r 1a Presidenciales 2017}
colnames(Gasto_primera_vuelta_presidencial_2017)
gasto_presidencial_2017 <- Gasto_primera_vuelta_presidencial_2017 %>% select(...4, ...2, ...3, ...14, ...15)

gasto_presidencial_2017_1 <- gasto_presidencial_2017 %>% rename(autoridad_electa = ...4,
                            region = ...2,
                            partido_politico = ...3,
                            glosa_del_gasto = ...14,
                            monto = ...15)

gasto_presidencial_2017_1 <- gasto_presidencial_2017_1 %>% select(-region)

gasto_digital_presidencial_2017 <- gasto_presidencial_2017_1 %>% filter(str_detect(glosa_del_gasto, regex("digital",ignore_case=T)))

rm(gasto_presidencial_2017, gasto_presidencial_2017_1)
```

```{r resultados gcc 2021}
resultados_constituyente <- read_excel("2021_05_CCG_Datos_Eleccion.xlsx")
result_constit <- resultados_constituyente %>% select(...2, ...7, ...8, ...13)

result_constit <- result_constit %>% rename(region = ...2,
                              pacto_electoral = ...7,
                              partido_político = ...8,
                              cantidad_votos = ...13)

result_constit <- result_constit[-(1:4), ]

resultado_constituyente_2021_r <- result_constit %>% group_by(region, partido_político) %>%
  summarize(votos_totales = sum(as.numeric(cantidad_votos),na.rm =T)) %>%
  ungroup()

resultado_constituyente_2021_p <- result_constit %>% group_by(partido_político) %>%
  summarize(votos_totales = sum(as.numeric(cantidad_votos),na.rm =T)) %>%
  ungroup()
rm(result_constit, resultados_constituyente)
```

```{r resultados parlamentarias 2021}
diputados_2021 <- read_excel("2021_11_Diputados_Datos_Eleccion.xlsx")

dip_2021 <- diputados_2021 %>% select(...2, ...7, ...8, ...13)

dip_2021 <- dip_2021 %>% rename(region = ...2,
                              pacto_electoral = ...7,
                              partido_político = ...8,
                              cantidad_votos = ...13) 

dip_2021 <- dip_2021[-(1:4), ]

resultados_diputados_2021_r <- dip_2021 %>% group_by(region, partido_político) %>%
  summarize(votos_totales = sum(as.numeric(cantidad_votos), na.rm=T)) %>%
  ungroup()

resultados_diputados_2021_p <- dip_2021 %>% group_by(partido_político) %>%
  summarize(votos_totales = sum(as.numeric(cantidad_votos), na.rm=T)) %>%
  ungroup()

rm(diputados_2021, dip_2021, resultados_diputados_2021)

senadores_2021 <- read_excel("2021_11_Senadores_Datos_Eleccion.xlsx")

sen_2021 <- senadores_2021 %>% select(...2, ...7, ...8, ...13)

sen_2021 <- sen_2021 %>% rename(region = ...2,
                              pacto_electoral = ...7,
                              partido_político = ...8,
                              cantidad_votos = ...13) 

sen_2021 <- sen_2021[-(1:4), ]

resultados_senador_2021_r <- sen_2021 %>% group_by(region, partido_político) %>%
  summarize(votos_totales = sum(as.numeric(cantidad_votos), na.rm=T)) %>%
  ungroup()

resultados_senador_2021_p <- sen_2021 %>% group_by(partido_político) %>%
  summarize(votos_totales = sum(as.numeric(cantidad_votos), na.rm=T)) %>%
  ungroup()

rm(senadores_2021, sen_2021)

#hay que unir las bases de datos de sen y dip, pero solo cuando escogamos los partidos con los que vamos a trabajar, así se hace mucho más fácil
```

```{r resultados presidenciales 2017}
primera_v_presidencial_2017 <- read_excel("2017_11_Presidencial_Datos_Eleccion.xlsx")
pp_2017 <- primera_v_presidencial_2017 %>% select(...2, ...11, ...13)

pp_2017 <- pp_2017 %>% rename(region = ...2,
                              primer_apellido = ...11,
                              cantidad_votos = ...13)

pp_2017 <- pp_2017[-(1:4), ]

resultados_primera_vuelta_pdte_2017 <- pp_2017 %>% group_by(primer_apellido) %>% 
  summarize(votos_totales = sum(as.numeric(cantidad_votos), na.rm=T)) %>%
  ungroup()

rm(primera_v_presidencial_2017, pp_2017)
```

```{r parlamentarias 2017}

```

```{r **}
rm(Gasto_Campaña_Parlamentarias_2017, Gasto_Campañas_Parlamentarias_2021, Gasto_Candidatos_Constitucionales_2021, Gasto_primera_vuelta_presidencial_2017)
```

