---
title: "Análisis inicial de bases"
output: html_document
date: "2025-10-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(janitor)
library(tidyverse)
library(skimr)
library (readxl)
library(writexl)
```

La importación de las bases se realizó con la función automática "import dataset..."

```{r Convencionales 2021}
colnames(Gasto_Candidatos_Constitucionales_2021)

gasto_constituyente_1 <- Gasto_Candidatos_Constitucionales_2021 %>% select(...2, ...3, ...9, ...19, ...20)

gasto_constituyentes_2 <- gasto_constituyente_1 %>% rename(autoridad_electa = ...2,
                      region = ...3,
                      partido_politico = ...9,
                      glosa_del_gasto = ...19,
                      monto_en_pesos = ...20)

gasto_constituyentes_2 <- gasto_constituyentes_2 %>% filter(autoridad_electa == "CONVENCIONAL CONSTITUYENTE")

gasto_digital_constituyentes_2021 <- gasto_constituyentes_2 %>% filter(str_detect(glosa_del_gasto, regex("digital", ignore_case = T)))

rm(gasto_constituyente_1, gasto_constituyentes_2)
```

```{r Parlamentarias 2021}
colnames(Gasto_Campañas_Parlamentarias_2021)

gasto_parlamentarias_1 <- Gasto_Campañas_Parlamentarias_2021 %>% select(...2,...3,...9,...19,...21)

gasto_parlamentarias_2 <- gasto_parlamentarias_1 %>% rename(autoridad_electa = ...2,
                      region = ...3,
                      partido_politico = ...9,
                      glosa_del_gasto = ...19,
                      monto = ...21)

gasto_digital_parlamentarias_2021 <- gasto_parlamentarias_2 %>% filter(str_detect(glosa_del_gasto, regex("digital", ignore_case = T)),
                               autoridad_electa %in% c("SENADOR", "DIPUTADO"))

rm(gasto_parlamentarias_1, gasto_parlamentarias_2)
```

```{r Parlamentarias 2017}
colnames(Gasto_Campaña_Parlamentarias_2017)

gasto_parlamentarias_1 <- Gasto_Campaña_Parlamentarias_2017 %>% select("PLANILLA DE GASTOS ELECCIONES PRESIDENCIAL Y PARLAMENTARIAS", ...2, ...8,...18, ...19)

gasto_parlamentarias_2 <- gasto_parlamentarias_1 %>% rename(autoridad_electa = "PLANILLA DE GASTOS ELECCIONES PRESIDENCIAL Y PARLAMENTARIAS",
                          region = ...2,
                          partido_politico = ...8,
                          glosa_del_gasto = ...18,
                          monto = ...19)

gasto_digital_parlamentarias_2017 <- gasto_parlamentarias_2 %>% filter(str_detect(glosa_del_gasto, regex("digital",ignore_case=T)),
                                   autoridad_electa %in% c("SENADOR", "DIPUTADO"))
rm(gasto_parlamentarias_1, gasto_parlamentarias_2)
```

```{r 1a Presidenciales 2017}
colnames(Gasto_primera_vuelta_presidencial_2017)
gasto_presidencial_2017 <- Gasto_primera_vuelta_presidencial_2017 %>% select(...4, ...2, ...3, ...14, ...15)

gasto_presidencial_2017_1 <- gasto_presidencial_2017 %>% rename(autoridad_electa = ...4,
                            region = ...2,
                            partido_politico = ...3,
                            glosa_del_gasto = ...14,
                            monto = ...15)

gasto_presidencial_2017_1 <- gasto_presidencial_2017_1 %>% select(-region)

gasto_digital_presidencial_2017 <- gasto_presidencial_2017_1 %>% filter(str_detect(glosa_del_gasto, regex("digital",ignore_case=T)))

rm(gasto_presidencial_2017, gasto_presidencial_2017_1)
```

```{r **}
rm(Gasto_Campaña_Parlamentarias_2017, Gasto_Campañas_Parlamentarias_2021, Gasto_Candidatos_Constitucionales_2021, Gasto_primera_vuelta_presidencial_2017)
```

```{r Unión de bases:output}

gasto_partido_constituyentes_2021_r <- gasto_digital_constituyentes_2021 %>%
  select(-autoridad_electa) %>%
  group_by(partido_politico, region) %>%
  summarize(gasto_digital_total = sum(as.numeric(monto_en_pesos), na.rm = T)) %>%
  ungroup()

gasto_partido_constituyentes_2021 <- gasto_digital_constituyentes_2021 %>%
  select(-autoridad_electa) %>%
  group_by(partido_politico) %>%
  summarize(gasto_digital_total = sum(as.numeric(monto_en_pesos), na.rm = T)) %>%
  ungroup()

gasto_partido_parlamentarias_2021_r <- gasto_digital_parlamentarias_2021 %>%
  select(-autoridad_electa) %>%
  group_by(partido_politico, region) %>%
  summarize(gasto_digital_total = sum(as.numeric(monto), na.rm = T)) %>%
  ungroup()

gasto_partido_parlamentarias_2021 <- gasto_digital_parlamentarias_2021 %>%
  select(-autoridad_electa) %>%
  group_by(partido_politico) %>%
  summarize(gasto_digital_total = sum(as.numeric(monto), na.rm = T)) %>%
  ungroup()

gasto_partido_parlamentarias_2017_r <- gasto_digital_parlamentarias_2017 %>%
  select(-autoridad_electa) %>%
  group_by(partido_politico, region) %>%
  summarize(gasto_digital_total = sum(as.numeric(monto), na.rm = T)) %>%
  ungroup()

gasto_partido_parlamentarias_2017 <- gasto_digital_parlamentarias_2017 %>%
  select(-autoridad_electa) %>%
  group_by(partido_politico) %>%
  summarize(gasto_digital_total = sum(as.numeric(monto), na.rm = T)) %>%
  ungroup()

gasto_partido_presidencial_2017 <- gasto_digital_presidencial_2017 %>%
  select(-autoridad_electa) %>%
  group_by(partido_politico) %>%
  summarize(gasto_digital_total = sum(as.numeric(monto), na.rm = T)) %>%
  ungroup()
```

```{r}
write_xlsx(gasto_partido_constituyentes_2021, path = "gasto_partido_constituyentes_2021.xlsx")
write_xlsx(gasto_partido_parlamentarias_2017, path = "gasto_partido_parlamentarias_2017.xlsx")
write_xlsx(gasto_partido_parlamentarias_2021, path = "gasto_partido_parlamentarias_2021.xlsx")
write_xlsx(gasto_partido_presidencial_2017, path = "gasto_partido_presidencial_2021.xlsx")
```

